# Importação das bibliotecas básicas

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Base de dados de crédito



### Exploração dos dados

In [ ]:
base_credit = pd.read_csv('credit_data.csv')

In [ ]:
base_credit

In [ ]:
base_credit.head(5)

In [ ]:
base_credit.tail(5)

In [ ]:
base_credit.describe()

In [ ]:
base_credit[base_credit['income'] >= 69995.685578]

In [ ]:
base_credit[base_credit['loan'] <= 1.377630]

### Visualização dos dados

In [ ]:
np.unique(base_credit['default'], return_counts=True)

In [ ]:
sns.countplot(x = base_credit['default']);

In [ ]:
plt.hist(x = base_credit['age']);

In [ ]:
plt.hist(x = base_credit['income']);

In [ ]:
plt.hist(x = base_credit['loan']);

In [ ]:
grafico = px.scatter_matrix(base_credit, dimensions=['age', 'income'], color = 'default')
grafico.show()

### Tratamento de valores inconsistentes

In [ ]:
base_credit.loc[base_credit['age'] < 0]

In [ ]:
base_credit[base_credit['age'] < 0]

In [ ]:
# Apagar a coluna inteira (de todos os registros da base de dados)
base_credit2 = base_credit.drop('age', axis = 1)
base_credit2

In [ ]:
# Apagar somente os registros com valores inconsistentes
base_credit3 = base_credit.drop(base_credit[base_credit['age'] < 0].index)
base_credit3

In [ ]:
base_credit3.loc[base_credit3['age'] < 0]

In [ ]:
# Preencher os valores inconsistente manualmente

In [ ]:
# Prencher a média

In [ ]:
base_credit.mean()

In [ ]:
base_credit['age'].mean()

In [ ]:
base_credit['age'][base_credit['age'] > 0].mean()

In [ ]:
base_credit.loc[base_credit['age'] < 0, 'age'] = 40.92

In [ ]:
base_credit.loc[base_credit['age'] < 0]

In [ ]:
base_credit.head(27)

### Tratamento de valores faltantes

In [ ]:
base_credit.isnull()

In [ ]:
base_credit.isnull().sum()

In [ ]:
base_credit.loc[pd.isnull(base_credit['age'])]

In [ ]:
base_credit['age'].fillna(base_credit['age'].mean(), inplace = True)

In [ ]:
base_credit.loc[pd.isnull(base_credit['age'])]

In [ ]:
base_credit.loc[(base_credit['clientid'] == 29) | (base_credit['clientid'] == 31) | (base_credit['clientid'] == 32)]

In [ ]:
base_credit.loc[base_credit['clientid'].isin([29, 31, 32])]

### Divisão entre previsores e classe

In [ ]:
type(base_credit)

In [ ]:
X_credit = base_credit.iloc[:, 1:4].values

In [ ]:
X_credit

In [ ]:
type(X_credit)

In [ ]:
y_credit = base_credit.iloc[:, 4].values

In [ ]:
y_credit

In [ ]:
type(y_credit)

### Escalonamento dos valores

In [ ]:
X_credit

In [ ]:
X_credit[:,0].min(), X_credit[:,1].min(), X_credit[:,2].min()

In [ ]:
X_credit[:,0].max(), X_credit[:,1].max(), X_credit[:,2].max()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_credit = StandardScaler()
X_credit = scaler_credit.fit_transform(X_credit)

In [ ]:
X_credit[:,0].min(), X_credit[:,1].min(), X_credit[:,2].min()

In [ ]:
X_credit[:,0].max(), X_credit[:,1].max(), X_credit[:,2].max()

In [ ]:
X_credit

### Subamostragem com Tomek Links

In [ ]:
from imblearn.under_sampling import TomekLinks

In [ ]:
tl = TomekLinks(sampling_strategy='majority') #all
X_under, y_under = tl.fit_resample(X_credit, y_credit)

In [46]:
X_under.shape, y_under.shape

((1993, 3), (1993,))

In [47]:
np.unique(y_credit, return_counts=True)

(array([0, 1]), array([1717,  283]))

In [48]:
np.unique(y_under, return_counts=True)

(array([0, 1]), array([1710,  283]))

### Sobreamostragem com SMOTE

In [49]:
from imblearn.over_sampling import SMOTE

In [52]:
X_credit.shape

(2000, 3)

In [50]:
smote = SMOTE(sampling_strategy='minority')
X_over, y_over = smote.fit_resample(X_credit, y_credit)

In [51]:
X_over.shape

(3434, 3)

In [53]:
np.unique(y_credit, return_counts=True)

(array([0, 1]), array([1717,  283]))

In [54]:
np.unique(y_over, return_counts=True)

(array([0, 1]), array([1717, 1717]))